repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

- repo: local
  hooks:
  - id: nixpkgs-fmt
    name: Nixpkgs Fmt
    entry: nixpkgs-fmt . --check
    language: system
    pass_filenames: false
    always_run: true

- repo: local
  hooks:
  - id: nix-flake-check
    name: Nix Flake Check
    entry: nix flake check --all-systems
    language: system
    pass_filenames: false
    always_run: true
