# Hyprland Wayland compositor
{ lib, config, pkgs, ... }@args:

let
  # Strip "#" — Hyprland color values use rgba(rrggbbaa)
  hex = c: lib.removePrefix "#" c;
  rgba = color: alpha: "rgba(${hex color}${alpha})";

  theme = lib.my.getTheme config;
  r = theme.roles;

  # Generate a Hyprland variables file sourced by hyprland.conf
  # Variables are prefixed with $hypr_ to avoid naming collisions.
  hyprTheme = ''
    # Generated by Nix — do not edit.
    # Change theme by updating theme.name in your host config.
    # Theme: ${theme.displayName}

    # ── Border colors ─────────────────────────────────────────────────────────
    $hypr_border_active   = ${rgba r.borderFocused "ee"}
    $hypr_border_inactive = ${rgba r.border "66"}

    # ── Shadow colors ──────────────────────────────────────────────────────────
    $hypr_shadow_color     = ${rgba r.background "cc"}
    $hypr_shadow_inactive  = ${rgba r.background "99"}
  '';
in
lib.my.mkModuleV2 args {
  platforms = [ "linux" ];
  description = "Hyprland Wayland compositor";

  # System-level configuration (requires root)
  systemModule = {
    nixosSystems = {
      # Enable Wayland and Hyprland
      programs.hyprland = {
        enable = true;
        withUWSM = true;
        xwayland.enable = true;
      };

      # Display Manager for Wayland
      services.greetd = {
        enable = true;
        settings = {
          default_session = {
            command = "${pkgs.tuigreet}/bin/tuigreet --time --cmd 'uwsm start hyprland-uwsm.desktop'";
            user = "greeter";
          };
        };
      };

      # Unlock gnome-keyring at login via PAM so tuigreet auto-unlocks it
      # using the user's login password — no separate keyring password prompt.
      security.pam.services.greetd.enableGnomeKeyring = true;

      # XDG portal for screen sharing and file dialogs
      xdg.portal = {
        enable = true;
        extraPortals = with pkgs; [
          xdg-desktop-portal-hyprland
          xdg-desktop-portal-gtk
        ];
      };

      # Keyboard layout (for Wayland)
      services.xserver = {
        enable = lib.mkDefault false;
        xkb = {
          layout = "us,ru";
          variant = ",mac";
          options = "grp:alt_space_toggle";
        };
      };

      # Console keyboard layout
      console.keyMap = "us";

      # Fonts for Waybar and other UI elements
      fonts.packages = with pkgs; [
        font-awesome
        nerd-fonts.jetbrains-mono
        nerd-fonts.fira-code
      ];
    };
  };

  module = {
    nixosSystems = {
      # Start gnome-keyring daemon as a user systemd service.
      # Provides the Secret Service D-Bus API that Electron apps use
      # to store credentials (VS Code, Antigravity IDE, Chrome, etc.).
      services.gnome-keyring = {
        enable = true;
        components = [ "secrets" "ssh" ];
      };

      # gcr provides the GUI unlock prompter (fallback if PAM didn't unlock)
      home.packages = [ pkgs.gcr ];

      # Generated Hyprland theme variables file.
      # Written to ~/.config/hypr-theme (adjacent to the live-editable
      # ~/.config/hypr symlink) to avoid the dir-level symlink conflict.
      # hyprland.conf sources this file to pick up $hypr_* variables.
      xdg.configFile."hypr-theme".text = hyprTheme;
    };
  };

  # Dotfiles symlink (live-editable)
  dotfiles = {
    path = "hypr";
    source = "modules/home/desktop/hyprland/dotfiles";
  };
}
