# Ghostty terminal emulator
{ lib, config, pkgs, ... }@args:

let
  # Strip leading "#" — Ghostty color values don't use the hash prefix
  hex = c: lib.removePrefix "#" c;

  # Generate a Ghostty theme file from a theme attrset
  mkGhosttyTheme = theme:
    let t = theme.terminal; p = theme.colors;
    in ''
      # Generated by Nix — do not edit.
      # Change theme by updating theme.name in your host config.
      palette = 0=${hex t.black}
      palette = 1=${hex t.red}
      palette = 2=${hex t.green}
      palette = 3=${hex t.yellow}
      palette = 4=${hex t.blue}
      palette = 5=${hex t.magenta}
      palette = 6=${hex t.cyan}
      palette = 7=${hex t.white}
      palette = 8=${hex t.brightBlack}
      palette = 9=${hex t.brightRed}
      palette = 10=${hex t.brightGreen}
      palette = 11=${hex t.brightYellow}
      palette = 12=${hex t.brightBlue}
      palette = 13=${hex t.brightMagenta}
      palette = 14=${hex t.brightCyan}
      palette = 15=${hex t.brightWhite}
      background = ${hex t.background}
      foreground = ${hex t.foreground}
      cursor-color = ${hex t.cursor}
      cursor-text = ${hex t.cursorText}
      selection-background = ${hex t.selection}
      selection-foreground = ${hex t.selectionText}
      split-divider-color = ${hex theme.roles.border}
    '';

  theme = lib.my.getTheme config;
in
lib.my.mkModuleV2 args {
  description = "Ghostty terminal emulator";
  module = {
    # Generated theme file — written by Nix, sourced by config via config-file = theme
    # Works on both NixOS and Darwin (xdg.configFile is cross-platform in home-manager)
    allSystems.xdg.configFile."ghostty/theme".text = mkGhosttyTheme theme;

    nixosSystems.home.packages = [ pkgs.ghostty ];
    darwinSystems.homebrew.casks = [ "ghostty" ];
  };

  # Symlink only the config file so home-manager can also write ghostty/theme
  dotfiles = {
    path = "ghostty/config";
    source = "modules/home/terminal/ghostty/dotfiles/config";
  };
}
