# Application launcher — Rofi (Wayland)
{ lib, config, pkgs, ... }@args:

let
  theme = lib.my.getTheme config;
  r = theme.roles;
  f = theme.fonts;

  # ── Rofi theme file (colors + widget layout) ────────────────────────────
  # Generated from the active Nix theme. Imported by config.rasi.
  rofiTheme = ''
    /**
     * Generated by Nix — do not edit.
     * Theme: ${theme.displayName}
     * Variant: ${theme.variant}
     * Change by setting theme.name in your host config.
     */

    * {
        /* ── Palette ─────────────────────────────────────────────────── */
        bg:          ${r.background};
        bg-alt:      ${r.backgroundAlt};
        bg-float:    ${r.backgroundFloat};
        bg-select:   ${r.selection};

        fg:          ${r.foreground};
        fg-muted:    ${r.foregroundMuted};
        fg-dim:      ${r.foregroundDim};

        accent:      ${r.accent};
        accent-alt:  ${r.accentAlt};
        clr-error:   ${r.error};

        /* Required Rofi wildcard properties */
        background-color: transparent;
        text-color:       @fg;
        font:             "${f.mono} 12";
    }

    window {
        background-color: @bg;
        border:           2px solid;
        border-color:     @accent;
        border-radius:    12px;
        padding:          0px;
        width:            600px;
    }

    mainbox {
        background-color: transparent;
        children:         [ inputbar, listview ];
        spacing:          0px;
    }

    /* ── Search bar ──────────────────────────────────────────────────────── */
    inputbar {
        background-color: @bg-alt;
        border-radius:    12px 12px 0px 0px;
        padding:          12px 16px;
        spacing:          8px;
        children:         [ prompt, entry ];
    }

    prompt {
        text-color: @accent;
        font:       "${f.mono} Bold 12";
    }

    entry {
        text-color:        @fg;
        placeholder:       "Search applications…";
        placeholder-color: @fg-dim;
        cursor:            text;
    }

    /* ── Results list ────────────────────────────────────────────────────── */
    listview {
        background-color: transparent;
        columns:          1;
        lines:            8;
        scrollbar:        false;
        spacing:          2px;
        padding:          8px;
        border-radius:    0px 0px 12px 12px;
    }

    element {
        background-color: transparent;
        border-radius:    8px;
        padding:          8px 12px;
        spacing:          10px;
        children:         [ element-icon, element-text ];
    }

    element normal.normal,
    element alternate.normal {
        background-color: transparent;
        text-color:       @fg;
    }

    element selected.normal {
        background-color: @bg-select;
        text-color:       @fg;
    }

    element normal.active,
    element alternate.active {
        background-color: transparent;
        text-color:       @accent;
    }

    element selected.active {
        background-color: @bg-select;
        text-color:       @accent;
    }

    element normal.urgent,
    element selected.urgent {
        background-color: @bg-select;
        text-color:       @clr-error;
    }

    element-icon {
        size:             20px;
        vertical-align:   0.5;
    }

    element-text {
        text-color: inherit;
        expand:     true;
        highlight:  bold ${r.accent};
    }

    /* ── Scrollbar (hidden but defined) ──────────────────────────────────── */
    scrollbar {
        background-color: @bg-alt;
        handle-color:     @fg-dim;
        handle-width:     4px;
        border-radius:    2px;
        width:            6px;
    }
  '';

  # ── Rofi config (settings + theme import) ───────────────────────────────
  # @import pulls in the generated theme.rasi from the same directory.
  rofiConfig = ''
    /**
     * Rofi configuration — managed by Nix (launcher.nix)
     * Theme colors come from @import "theme.rasi"
     */
    configuration {
        modi:               "drun,run";
        show-icons:         true;
        display-drun:       "  Apps";
        display-run:        "  Run";
        drun-display-format: "{name}";
        hover-select:       false;
        /* Accept entry on primary click */
        me-select-entry:    "";
        me-accept-entry:    "MousePrimary";
    }

    @import "theme.rasi"
  '';
in
lib.my.mkModuleV2 args {
  platforms = [ "linux" ];
  description = "Application launcher (rofi)";

  module = {
    nixosSystems = {
      # rofi-wayland: native Wayland fork of rofi, required for Hyprland
      home.packages = [ pkgs.rofi ];

      # Both files are fully Nix-managed — no dotfiles dir symlink needed.
      # Switching themes only requires changing theme.name in the host config.
      xdg.configFile."rofi/theme.rasi".text = rofiTheme;
      xdg.configFile."rofi/config.rasi".text = rofiConfig;
    };
  };
}
