# Waybar - Wayland status bar
{ lib, config, pkgs, ... }@args:

let
  theme = lib.my.getTheme config;
  r = theme.roles;

  # ── Generated GTK CSS theme file ──────────────────────────────────────────
  # Written to ~/.config/waybar-theme.css (adjacent to the ~/.config/waybar
  # symlink) to avoid the dir-level symlink conflict — same pattern as hypr-theme.
  # style.css imports it with: @import "../waybar-theme.css";
  waybartheme = ''
    /**
     * Generated by Nix — do not edit.
     * Theme: ${theme.displayName}
     * Variant: ${theme.variant}
     * Change by setting theme.name in your host config.
     */

    /* ── Core background / foreground ────────────────────────────────────── */
    @define-color background  ${r.background};
    @define-color foreground  ${r.foreground};

    /* ── Aliases used throughout style.css ───────────────────────────────── */
    @define-color bg          ${r.background};
    @define-color fg          ${r.foreground};

    /* ── Accent (replaces the hardcoded #df6124 orange) ─────────────────── */
    @define-color red         ${r.accent};

    /* ── Surface / muted tones ───────────────────────────────────────────── */
    @define-color grey        ${r.foregroundMuted};
    @define-color grey2       ${r.backgroundFloat};

    /* ── Semantic roles ──────────────────────────────────────────────────── */
    @define-color surface     ${r.backgroundAlt};
    @define-color overlay     ${r.backgroundFloat};
    @define-color border      ${r.border};
    @define-color accent      ${r.accent};
    @define-color accent-alt  ${r.accentAlt};
    @define-color clr-error   ${r.error};
    @define-color clr-warning ${r.warning};
    @define-color clr-success ${r.success};
  '';
in
lib.my.mkModuleV2 args {
  platforms = [ "linux" ];
  description = "Waybar status bar for Wayland";

  module = {
    nixosSystems = {
      home.packages = with pkgs; [
        waybar
        # Dependencies for waybar modules
        pamixer # pulseaudio volume control
        brightnessctl # backlight
        pavucontrol # pulseaudio GUI (on-click)
      ];

      # Generated theme CSS — written adjacent to the waybar dotfiles symlink
      # so @import "../waybar-theme.css" resolves correctly from style.css.
      xdg.configFile."waybar-theme.css".text = waybartheme;
    };
  };

  dotfiles = {
    path = "waybar";
    source = "modules/home/desktop/hyprland/dotfiles/waybar";
  };
}
